### ISSUE TITLE
Feature Request: Update batch ?

### ISSUE THREAD

**Issue by viezel** [tkjaergaard/Economic-PHP-SDK#16]
Hi Thomas,

First off - Great package! 

While I used your package I saw that it uses many http requests to update a single item (product/debtor). I see you use a lot of switch cases to do so. 

Would you be interested in create more effiecient methods to keep the all the network requests to a mimimum? 
Economics has endpoints for this purpose, e.g. `Debtor_UpdateFromData` and `Debtor_CreateFromData` etc. 

```
 $debitor_handle = $this->client->Debtor_UpdateFromData([
        'data' => (object) [
            'Handle' => $debitor,
            'Number' => $debitor->Number,
            'VatZone' => $vat_zone,
            'IsAccessible' => true,
            'Name' => $params['company'],
            'Email' => $params['email'],
            'CINumber' => $params['vat'],
            'Address' => $params['address'],
            'PostalCode' => $params['postalcode'],
            'City' => $params['city'],
            'Country' => $params['country'],
            'DebtorGroupHandle' => $groupHandles,
            'CurrencyHandle' => $currencyHandle,
            'TermOfPaymentHandle' => $termHandle,
            'LayoutHandle' => $templatecollectionHandle,
            'AttentionHandle' => $contact_handle
        ],
 ])->Debtor_UpdateFromDataResult;
```

It would make the package much more complete. 

ref: https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=Debtor_UpdateFromData

**Comment by tkjaergaard** [comment]
Yep, I'm aware of this "issue", and there could definitely be done something about the number of http request in both create and update methods. I'll might take a look at it, otherwise, you're more than welcome to throw a PR ;) :+1:

**Comment by viezel** [comment]
@tkjaergaard sweet. That could be cool. 
We are also working on supporting multiple currencies on product prices atm.

**Comment by Svenn1** [comment]
@tkjaergaard Hey there, i'm totally intruding on this conversation <3

Here is a pull request that serves as a good base for a bulk update method:

https://github.com/tkjaergaard/Economic-PHP-SDK/pull/17
