### ISSUE TITLE
Token login

### ISSUE THREAD

**Issue by canfiax** [tkjaergaard/Economic-PHP-SDK#23]
Does this package support login with Token?

If not, it could be a really good feature to implement. Economic only features apps on their appstore that uses this login. The login with credentials is an old and soon to be deprecated login method.

**Comment by tkjaergaard** [comment]
https://github.com/tkjaergaard/Economic-PHP-SDK/blob/master/docs/GettingStarted.md

**Comment by canfiax** [comment]
Great! Good job!
