### ISSUE TITLE
Is CashBookEntry not implemented?

### ISSUE THREAD

**Issue by NobrainerWeb** [tkjaergaard/Economic-PHP-SDK#26]
Looking at the code i see no reference of CashBookEntry_*
Is this something that is not implemented, or am i missing something?
Looking to push some CashBookEntries from a PHP shop to e-conomic, and would like to use this wrapper.

**Comment by tkjaergaard** [comment]
Hi @NobrainerWeb,

Unfortunately the ChashBook is not implemented.

You're more than welcome to make a PR with some code for me to look at 🙂

This implementation is not in the road map for the lib, and i'm currently working on a version 3, which is not planned to include CashBook either in it's first release.

Sorry ✌️

**Comment by NobrainerWeb** [comment]
Thank you for you answer - do you have any pointers as to how we would best implement the missing CashBookEntry stuff?

**Comment by tkjaergaard** [comment]
This lib uses the E-conomic SOAP api, which is "documented" here https://api.e-conomic.com/secure/api1/EconomicWebService.asmx

They also after the creation of this lib gotten a REST API https://restdocs.e-conomic.com/ – but it doesn't seems like the CashBook endpoint is either not docuemented or implemented.

The way I've done it with this lib, is to respect the classes like `CashBook` and `CashBookEntry` and create the necessary wrapper functions to create a cleaner API to work with.

Happy coding 🙌 👏

**Comment by NobrainerWeb** [comment]
Thank you for your answers - e-conomics confirmed the REST api does not have the CashBook implemented, so SOAP is the way to go.

**Comment by manoakys** [comment]
Just an update -  e-conomics confirmed me, that REST api will have CashBook implemented in 2017 Q1.
