### ISSUE TITLE
Package does not work anymore, because URL of wsdl has been changed

### ISSUE THREAD

**Issue by pbrzoski** [tkjaergaard/Economic-PHP-SDK#32]
As you can see on https://twitter.com/economicAPI/status/847018520332451842, the wsdl url has been changed to 

https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?wsdl

**Comment by tkjaergaard** [comment]
Fixed in latest version: https://github.com/tkjaergaard/Economic-PHP-SDK/pull/31

**Comment by pbrzoski** [comment]
Thanks :)
